from tkinter import *
from Functions import *
from tkinter import ttk
from PIL import Image, ImageTk


def entra():
    login = En_login.get()
    senha = En_senha.get()
    if login == "mano" and senha == "123":
        print('Entrou')


def tela1():
    tela = Tk()
    tela.title("Login")
    tela.geometry("310x316+689+288")
    tela.configure(background="#c0c0c0")

    global En_senha,En_login,var_slv_login

    var_slv_login = IntVar()

    fr_telalogin = Frame(tela)
    fr_telalogin.place(relx=0.029, rely=0.028, relheight=0.937, relwidth=0.948)
    fr_telalogin = Frames(fr_telalogin, bg="#63a6dc", relevo="groove", borda="2").config()

    En_login = Entry(fr_telalogin)
    En_login.place(relx=0.34, rely=0.49, height=20, relwidth=0.524)
    En_login.configure(background="white")
    En_login.configure(foreground="#000000")
    En_login.configure(font="TkFixedFont")

    En_senha = Entry(fr_telalogin)
    En_senha.place(relx=0.34, rely=0.595, height=20, relwidth=0.524)
    En_senha.configure(background="white")
    En_senha.configure(foreground="#000000")
    En_senha.configure(font="TkFixedFont")
    En_senha.configure(show="*")

    msg_login = Message(fr_telalogin)
    msg_login.place(relx=0.102, rely=0.456, relheight=0.115, relwidth=0.204)
    Mensagens(msg_login, msg="Login :", bg="#63a6dc", fg="#000000", tam=11).config()

    msg_senha = Message(fr_telalogin)
    msg_senha.place(relx=0.102, rely=0.595, relheight=0.081, relwidth=0.204)
    Mensagens(msg_senha, msg="Senha :", bg="#63a6dc", fg="#000000", tam=11).config()

    cb_slv_login = Checkbutton(fr_telalogin)
    cb_slv_login.place(relx=0.16, rely=0.709, relheight=0.088, relwidth=0.204)
    cb_slv_login.configure(activebackground="#63a6dc")
    cb_slv_login.configure(activeforeground="#000000")
    cb_slv_login.configure(background="#63a6dc")
    cb_slv_login.configure(disabledforeground="#a3a3a3")
    cb_slv_login.configure(foreground="#000000")
    cb_slv_login.configure(highlightbackground="#d9d9d9")
    cb_slv_login.configure(highlightcolor="black")
    cb_slv_login.configure(text="Salvar")
    cb_slv_login.configure(onvalue=1)
    cb_slv_login.configure(offvalue=0)

    bt_entra = Button(fr_telalogin)
    bt_entra.place(relx=0.412, rely=0.807, height=25, width=76)
    Botoes(bt_entra, "Entra", entra).config(bg="#d9d9d9", fg="#000000")

    fr_molduraa = Frame(fr_telalogin)
    fr_molduraa.place(relx=0.35, rely=0.064, relheight=0.334, relwidth=0.357)
    fr_molduraa.config(background="#000000")
    fr_molduraa.config(relief="groove")
    fr_molduraa.config(border="2")

    img = ImageTk.PhotoImage(Image.open("logo.jpg"))
    imglabel = Label(fr_molduraa, image=img)
    imglabel.place(relx=-0.584, rely=-0.111, height=130, width=225)
    imglabel.configure(background="#ffffff")


app = Tk()
app.title("Login")
app.geometry("804x588+455+190")
app.configure(background="#ffffff")

fr_formas_paga = Frame(app)
fr_formas_paga.place(relx=0.516, rely=0.27, relheight=0.35, relwidth=0.473)
fr_formas_paga.configure(relief='flat')
fr_formas_paga.configure(borderwidth="2")
fr_formas_paga.configure(background="#ffffff")

rd_dinheiro = Radiobutton(fr_formas_paga)
rd_dinheiro.place(relx=0.026, rely=0.291, relheight=0.17, relwidth=0.25)
rd_dinheiro.configure(activebackground="#ececec")
rd_dinheiro.configure(activeforeground="#000000")
rd_dinheiro.configure(background="#ffffff")
rd_dinheiro.configure(disabledforeground="#a3a3a3")
rd_dinheiro.configure(font="font9")
rd_dinheiro.configure(foreground="#000000")
rd_dinheiro.configure(highlightbackground="#d9d9d9")
rd_dinheiro.configure(highlightcolor="black")
rd_dinheiro.configure(justify='left')
rd_dinheiro.configure(text='''Dinheiro''')
#rd_dinheiro.configure(variable=)

fr_credito = Frame(fr_formas_paga)
fr_credito.place(relx=0.526, rely=0.534, relheight=0.413, relwidth=0.476)
fr_credito.configure(relief='groove')
fr_credito.configure(borderwidth="2")
fr_credito.configure(relief="groove")
fr_credito.configure(background="#63a6dc")

rb_credito = Radiobutton(fr_credito)
rb_credito.place(relx=0.221, rely=0.118, relheight=0.176, relwidth=0.47)
rb_credito.configure(activebackground="#ececec")
rb_credito.configure(activeforeground="#000000")
rb_credito.configure(background="#63a6dc")
rb_credito.configure(disabledforeground="#a3a3a3")
rb_credito.configure(font="-family {Segoe UI} -size 12 -weight bold")
rb_credito.configure(foreground="#000000")
rb_credito.configure(highlightbackground="#d9d9d9")
rb_credito.configure(highlightcolor="black")
rb_credito.configure(justify='left')
rb_credito.configure(text='''Credito''')
#rb_credito.configure(variable=vr_fpagamentos)

msg_nome = Message(fr_credito)
msg_nome.place(relx=0.055, rely=0.353, relheight=0.153, relwidth=0.663)
msg_nome.configure(background="#63a6dc")
msg_nome.configure(font="font13")
msg_nome.configure(foreground="#000000")
msg_nome.configure(highlightbackground="#d9d9d9")
msg_nome.configure(highlightcolor="black")
msg_nome.configure(text='''Nome do Cliente:''')
msg_nome.configure(width=120)

en_nome = Entry(fr_credito)
en_nome.place(relx=0.055, rely=0.588, height=20, relwidth=0.851)
en_nome.configure(background="white")
en_nome.configure(disabledforeground="#a3a3a3")
en_nome.configure(font="TkFixedFont")
en_nome.configure(foreground="#000000")
en_nome.configure(highlightbackground="#d9d9d9")
en_nome.configure(highlightcolor="black")
en_nome.configure(insertbackground="black")
en_nome.configure(selectbackground="#c4c4c4")
en_nome.configure(selectforeground="black")

fr_cartao = Frame(fr_formas_paga)
fr_cartao.place(relx=0.0, rely=0.534, relheight=0.413, relwidth=0.503)
fr_cartao.configure(relief='groove')
fr_cartao.configure(borderwidth="2")
fr_cartao.configure(relief="groove")
fr_cartao.configure(background="#63a6dc")
fr_cartao.configure(highlightbackground="#d9d9d9")
fr_cartao.configure(highlightcolor="black")

cb_parcelas = ttk.Combobox(fr_cartao)
cb_parcelas.place(relx=0.058, rely=0.588, relheight=0.247, relwidth=0.901)
#cb_parcelas.configure(textvariable=unknown_support.combobox)
cb_parcelas.configure(takefocus="")

msg_parcelas = Message(fr_cartao)
msg_parcelas.place(relx=0.058, rely=0.353, relheight=0.153, relwidth=0.607)
msg_parcelas.configure(background="#63a6dc")
msg_parcelas.configure(font="-family {Segoe UI} -size 10 -weight bold")
msg_parcelas.configure(foreground="#000000")
msg_parcelas.configure(highlightbackground="#d9d9d9")
msg_parcelas.configure(highlightcolor="black")
msg_parcelas.configure(text='''Qnt de Parcelas:''')
msg_parcelas.configure(width=110)

rb_cartao = Radiobutton(fr_cartao)
rb_cartao.place(relx=0.209, rely=0.118, relheight=0.176, relwidth=0.476)
rb_cartao.configure(activebackground="#ececec")
rb_cartao.configure(activeforeground="#000000")
rb_cartao.configure(background="#63a6dc")
rb_cartao.configure(disabledforeground="#a3a3a3")
rb_cartao.configure(font="-family {Segoe UI} -size 12 -weight bold")
rb_cartao.configure(foreground="#000000")
rb_cartao.configure(highlightbackground="#d9d9d9")
rb_cartao.configure(highlightcolor="black")
rb_cartao.configure(justify='left')
rb_cartao.configure(text='''Cartão''')
#rb_cartao.configure(variable=unknown_support.vr_fpagamentos)

fr_hora_data = Frame(fr_formas_paga)
fr_hora_data.place(relx=0.526, rely=0.049, relheight=0.413, relwidth=0.476)
fr_hora_data.configure(relief='groove')
fr_hora_data.configure(borderwidth="2")
fr_hora_data.configure(relief="groove")
fr_hora_data.configure(background="#e9a506")
fr_hora_data.configure(highlightbackground="#d9d9d9")
fr_hora_data.configure(highlightcolor="black")

msg_data = Message(fr_hora_data)
msg_data.place(relx=0.166, rely=0.118, relheight=0.271, relwidth=0.702)
msg_data.configure(background="#e9a506")
msg_data.configure(font="font15")
msg_data.configure(foreground="#000000")
msg_data.configure(highlightbackground="#d9d9d9")
msg_data.configure(highlightcolor="black")
msg_data.configure(text='''12/22/88''')
msg_data.configure(width=120)

msg_hora = Message(fr_hora_data)
msg_hora.place(relx=0.276, rely=0.471, relheight=0.271, relwidth=0.514)
msg_hora.configure(background="#e9a506")
msg_hora.configure(font="font16")
msg_hora.configure(foreground="#000000")
msg_hora.configure(highlightbackground="#d9d9d9")
msg_hora.configure(highlightcolor="black")
msg_hora.configure(text='''22:56:55''')
msg_hora.configure(width=93)

lb_img_vendas = Label(fr_formas_paga)
lb_img_vendas.place(relx=0.053, rely=0.0, height=51, width=156)
lb_img_vendas.configure(background="#d9d9d9")
lb_img_vendas.configure(disabledforeground="#a3a3a3")
lb_img_vendas.configure(foreground="#000000")
img0 = ImageTk.PhotoImage(Image.open("vendas.png"))
lb_img_vendas.configure(image=img0)
lb_img_vendas.configure(text='''Label''')

lb_img_carrinho = Label(fr_formas_paga)
lb_img_carrinho.place(relx=0.368, rely=0.243, height=41, width=44)
lb_img_carrinho.configure(background="#d9d9d9")
lb_img_carrinho.configure(disabledforeground="#a3a3a3")
lb_img_carrinho.configure(foreground="#000000")
img1 = ImageTk.PhotoImage(Image.open("carrinho.jpg"))
lb_img_carrinho.configure(image=img1)
lb_img_carrinho.configure(text='''Label''')

fr_troco = Frame(app)
fr_troco.place(relx=0.516, rely=0.629, relheight=0.35, relwidth=0.473)
fr_troco.configure(relief='groove')
fr_troco.configure(borderwidth="2")
fr_troco.configure(relief="groove")
fr_troco.configure(background="#63a6dc")

fr_totall = ttk.Frame(fr_troco)
fr_totall.place(relx=0.211, rely=0.34, relheight=0.413, relwidth=0.618)
fr_totall.configure(relief='raised')
fr_totall.configure(borderwidth="2")
fr_totall.configure(relief="raised")

msg_000 = Message(fr_totall)
msg_000.place(relx=0.426, rely=0.235, relheight=0.506, relwidth=0.43)
msg_000.configure(background="#10a060")
msg_000.configure(font="-family {Segoe UI} -size 23 -weight bold")
msg_000.configure(foreground="#000000")
msg_000.configure(highlightbackground="#d9d9d9")
msg_000.configure(highlightcolor="black")
msg_000.configure(text='''00,00''')
msg_000.configure(width=101)

msg_rss = Message(fr_totall)
msg_rss.place(relx=0.17, rely=0.235, relheight=0.506, relwidth=0.213)
msg_rss.configure(background="#10a060")
msg_rss.configure(font="-family {Segoe UI} -size 23 -weight bold")
msg_rss.configure(foreground="#000000")
msg_rss.configure(highlightbackground="#d9d9d9")
msg_rss.configure(highlightcolor="black")
msg_rss.configure(text='''R$''')
msg_rss.configure(width=50)

bt_finalizar = ttk.Button(fr_troco)
bt_finalizar.place(relx=0.421, rely=0.777, height=35, width=76)
bt_finalizar.configure(takefocus="")
bt_finalizar.configure(text='''Finalizar''')

en_troco = Entry(fr_troco)
en_troco.place(relx=0.079, rely=0.146, height=20, relwidth=0.511)
en_troco.configure(background="white")
en_troco.configure(disabledforeground="#a3a3a3")
en_troco.configure(font="TkFixedFont")
en_troco.configure(foreground="#000000")
en_troco.configure(insertbackground="black")

bt_calcular = ttk.Button(fr_troco)
bt_calcular.place(relx=0.658, rely=0.146, height=25, width=76)
bt_calcular.configure(takefocus="")
bt_calcular.configure(text='''Calcular''')

Message1 = Message(fr_troco)
Message1.place(relx=0.079, rely=0.049, relheight=0.063, relwidth=0.316)
Message1.configure(background="#63a6dc")
Message1.configure(font="font10")
Message1.configure(foreground="#000000")
Message1.configure(highlightbackground="#d9d9d9")
Message1.configure(highlightcolor="black")
Message1.configure(text='''Calcular Troco :''')
Message1.configure(width=120)

fr_detalhes = Frame(app)
fr_detalhes.place(relx=0.012, rely=0.27, relheight=0.709, relwidth=0.499)
fr_detalhes.configure(relief='groove')
fr_detalhes.configure(borderwidth="2")
fr_detalhes.configure(relief="groove")
fr_detalhes.configure(background="#63a6dc")

fr_tvv = Frame(fr_detalhes)
fr_tvv.place(relx=0.025, rely=0.144, relheight=0.612, relwidth=0.935)
fr_tvv.configure(relief='groove')
fr_tvv.configure(borderwidth="2")
fr_tvv.configure(relief="groove")
fr_tvv.configure(background="#d9d9d9")

en_produtos = Entry(fr_detalhes)
en_produtos.place(relx=0.125, rely=0.072, height=20, relwidth=0.334)
en_produtos.configure(background="white")
en_produtos.configure(disabledforeground="#a3a3a3")
en_produtos.configure(font="TkFixedFont")
en_produtos.configure(foreground="#000000")
en_produtos.configure(insertbackground="black")

en_valor = Entry(fr_detalhes)
en_valor.place(relx=0.474, rely=0.072, height=20, relwidth=0.309)
en_valor.configure(background="white")
en_valor.configure(disabledforeground="#a3a3a3")
en_valor.configure(font="TkFixedFont")
en_valor.configure(foreground="#000000")
en_valor.configure(insertbackground="black")

bt_adicionar = Button(fr_detalhes)
bt_adicionar.place(relx=0.798, rely=0.072, height=25, width=66)
bt_adicionar.configure(takefocus="")
bt_adicionar.configure(text='''Adicionar''')

sb_qtn = Spinbox(fr_detalhes, from_=1.0, to=100.0)
sb_qtn.place(relx=0.05, rely=0.072, relheight=0.046, relwidth=0.062)
sb_qtn.configure(activebackground="#f9f9f9")
sb_qtn.configure(background="white")
sb_qtn.configure(buttonbackground="#d9d9d9")
sb_qtn.configure(disabledforeground="#a3a3a3")
sb_qtn.configure(font="TkDefaultFont")
sb_qtn.configure(foreground="black")
sb_qtn.configure(highlightbackground="black")
sb_qtn.configure(highlightcolor="black")
sb_qtn.configure(insertbackground="black")
sb_qtn.configure(selectbackground="#c4c4c4")
sb_qtn.configure(selectforeground="black")
#sb_qtn.configure(textvariable=spinbox)

fr_total = Frame(fr_detalhes)
fr_total.place(relx=0.025, rely=0.767, relheight=0.204, relwidth=0.586)
fr_total.configure(relief='groove')
fr_total.configure(borderwidth="2")
fr_total.configure(relief="groove")

msg_rs = Message(fr_total)
msg_rs.place(relx=0.128, rely=0.235, relheight=0.506, relwidth=0.213)
msg_rs.configure(background="#10a060")
msg_rs.configure(foreground="#000000")
msg_rs.configure(highlightbackground="#d9d9d9")
msg_rs.configure(highlightcolor="black")
msg_rs.configure(text='''R$''')
msg_rs.configure(width=50)

msg_00 = Message(fr_total)
msg_00.place(relx=0.383, rely=0.235, relheight=0.506, relwidth=0.43)
msg_00.configure(background="#10a060")
msg_00.configure(foreground="#000000")
msg_00.configure(highlightbackground="#d9d9d9")
msg_00.configure(highlightcolor="black")
msg_00.configure(text='''00,00''')
msg_00.configure(width=101)

bt_remover = Button(fr_detalhes)
bt_remover.place(relx=0.723, rely=0.767, height=25, width=86)
bt_remover.configure(takefocus="")
bt_remover.configure(text='''Remover''')

bt_novacompra = Button(fr_detalhes)
bt_novacompra.place(relx=0.723, rely=0.911, height=25, width=84)
bt_novacompra.configure(takefocus="")
bt_novacompra.configure(text='''Nova Compra''')

bt_ntfiscal = Button(fr_detalhes)
bt_ntfiscal.place(relx=0.723, rely=0.839, height=25, width=86)
bt_ntfiscal.configure(takefocus="")
bt_ntfiscal.configure(text='''Nota Fiscal''')

msg_produtos = Message(fr_detalhes)
msg_produtos.place(relx=0.125, rely=0.024, relheight=0.031, relwidth=0.2)
msg_produtos.configure(background="#63a6dc")
msg_produtos.configure(foreground="#000000")
msg_produtos.configure(highlightbackground="#d9d9d9")
msg_produtos.configure(highlightcolor="black")
msg_produtos.configure(text='''Produtos''')
msg_produtos.configure(width=80)

msg_valor = Message(fr_detalhes)
msg_valor.place(relx=0.449, rely=0.024, relheight=0.031, relwidth=0.175)
msg_valor.configure(background="#63a6dc")
msg_valor.configure(foreground="#000000")
msg_valor.configure(highlightbackground="#d9d9d9")
msg_valor.configure(highlightcolor="black")
msg_valor.configure(text='''Valor''')
msg_valor.configure(width=70)

msg_qtd = Message(fr_detalhes)
msg_qtd.place(relx=0.025, rely=0.024, relheight=0.031, relwidth=0.092)
msg_qtd.configure(background="#63a6dc")
msg_qtd.configure(foreground="#000000")
msg_qtd.configure(highlightbackground="#d9d9d9")
msg_qtd.configure(highlightcolor="black")
msg_qtd.configure(text='''Qtd''')
msg_qtd.configure(width=37)

lb_sair = Label(app)
lb_sair.place(relx=-0.087, rely=-0.034, height=171, width=924)
lb_sair.configure(activebackground="#ffffff")
lb_sair.configure(background="#ffffff")
lb_sair.configure(disabledforeground="#a3a3a3")
lb_sair.configure(foreground="#000000")
img2 = ImageTk.PhotoImage(Image.open("logomarca.jpg"))
lb_sair.configure(image=img2)

app.mainloop()
